
package Interfaces.LoginUI;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author eduda
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButtonregistrarse = new javax.swing.JButton();
        jButtonIniciarsesion = new javax.swing.JButton();
        jTextusuario = new javax.swing.JTextField();
        jTextcontraseña = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel3.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonregistrarse.setBackground(new java.awt.Color(90, 113, 126));
        jButtonregistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonregistrarse.setText("Registrarse");
        jButtonregistrarse.setBorderPainted(false);
        jButtonregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 130, 30));

        jButtonIniciarsesion.setBackground(new java.awt.Color(3, 25, 38));
        jButtonIniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarsesion.setText("Iniciar sesión");
        jButtonIniciarsesion.setBorder(null);
        jButtonIniciarsesion.setBorderPainted(false);
        jPanel3.add(jButtonIniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 250, 50));

        jTextusuario.setText("Contraseña");
        jPanel3.add(jTextusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 300, 40));

        jTextcontraseña.setText("Usuario");
        jTextcontraseña.setFocusCycleRoot(true);
        jTextcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcontraseñaActionPerformed(evt);
            }
        });
        jPanel3.add(jTextcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 300, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Group 7.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 190, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Iniciar sesión.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 720));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcontraseñaActionPerformed

    private void jButtonregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarseActionPerformed
                frmRegistro fr=new frmRegistro();
        fr.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonregistrarseActionPerformed
private void ShowJPanel(JPanel p){
        p.setSize(647,645);
        p.setLocation(0, 0);
        
        jPanel3.removeAll();
        jPanel3.add(p, BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarsesion;
    private javax.swing.JButton jButtonregistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextcontraseña;
    private javax.swing.JTextField jTextusuario;
    // End of variables declaration//GEN-END:variables
}
