
package Interfaces.LoginUI;

import com.JuezCachimbo;
import com.usuarios.Student;
import com.usuarios.Teacher;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.io.*;
import java.util.Random;


/**
 *
 * @author eduda
 */
public class frmRegistro extends javax.swing.JFrame {

    public frmRegistro() {
        initComponents();    
        jLabel3.setVisible(false);
        jTextcarreraprof.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextaño = new javax.swing.JTextField();
        jTextNomyApelli = new javax.swing.JTextField();
        jButtonguardarregistro = new javax.swing.JButton();
        jRadioProfesoregister = new javax.swing.JRadioButton();
        jRadioEstudianteregister = new javax.swing.JRadioButton();
        jTextcontraseñaregistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextcarreraprof = new javax.swing.JTextField();
        jTextdia = new javax.swing.JTextField();
        jTextmes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextnameuserregister = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel3.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextaño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextaño.setText("Año");
        jTextaño.setFocusCycleRoot(true);
        jTextaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextañoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 70, 40));

        jTextNomyApelli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomyApelliActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNomyApelli, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 300, 30));

        jButtonguardarregistro.setBackground(new java.awt.Color(90, 113, 126));
        jButtonguardarregistro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonguardarregistro.setText("Registrarse");
        jButtonguardarregistro.setBorderPainted(false);
        jButtonguardarregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonguardarregistroActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonguardarregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 290, 40));

        buttonGroup1.add(jRadioProfesoregister);
        jRadioProfesoregister.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jRadioProfesoregister.setText("Profesor");
        jRadioProfesoregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProfesoregisterActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioProfesoregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        buttonGroup1.add(jRadioEstudianteregister);
        jRadioEstudianteregister.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jRadioEstudianteregister.setSelected(true);
        jRadioEstudianteregister.setText("Estudiante");
        jRadioEstudianteregister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 0));
        jRadioEstudianteregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEstudianteregisterActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioEstudianteregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jTextcontraseñaregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcontraseñaregistroActionPerformed(evt);
            }
        });
        jPanel1.add(jTextcontraseñaregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 300, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Fecha de nacimiento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 220, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Carrera profesional:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 180, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Nombres y apellidos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, -1));

        jTextcarreraprof.setFocusCycleRoot(true);
        jTextcarreraprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcarreraprofActionPerformed(evt);
            }
        });
        jPanel1.add(jTextcarreraprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 310, 30));

        jTextdia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextdia.setText("Dia");
        jTextdia.setFocusCycleRoot(true);
        jTextdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdiaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 70, 40));

        jTextmes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextmes.setText("Mes");
        jTextmes.setFocusCycleRoot(true);
        jTextmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextmesActionPerformed(evt);
            }
        });
        jPanel1.add(jTextmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 70, 40));

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 36)); // NOI18N
        jLabel6.setText("//");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 40, 40));

        jLabel7.setFont(new java.awt.Font("SimSun-ExtB", 0, 36)); // NOI18N
        jLabel7.setText("//");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 40, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Nombre de usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 190, -1));

        jTextnameuserregister.setFocusCycleRoot(true);
        jTextnameuserregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnameuserregisterActionPerformed(evt);
            }
        });
        jPanel1.add(jTextnameuserregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 310, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 740, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Registro.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1110, 830));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void guardarUsuario(String username, String password, String rutaObjeto, String tipo) {
        String linea = username+","+"password"+","+tipo;
        String ruta = "src/data/Listas/userList.txt";
        
        try (BufferedReader br = new BufferedReader(new FileReader(ruta));
            BufferedWriter bw = new BufferedWriter(new FileWriter(ruta, true))) {
            bw.write(linea);
            bw.newLine();
            bw.write(rutaObjeto);
            bw.newLine();
            bw.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void jTextañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextañoActionPerformed
    private static String generarNombreAleatorio() {
            Random random = new Random();
            int num = random.nextInt(100000); 
            return "usuario_" + num; 
    }
    
    private void jButtonguardarregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonguardarregistroActionPerformed
        String usuario = jTextnameuserregister.getText();
        String contraseña = jTextcontraseñaregistro.getText();
        String nombre = jTextNomyApelli.getText();
        String fecha = jTextdia.getText() + "/" + jTextmes.getText() + "/" + jTextaño.getText();
        String carrera = jTextcarreraprof.getText();
        String tipo = "";
        String nombreArchivo = generarNombreAleatorio() + ".txt";
        String rutaCompleta = "src/data/Usuarios/" + nombreArchivo;

        Object user;
        if (jRadioEstudianteregister.isSelected()) {
            user = new Student();
            ((Student) user).setUserName(usuario);
            ((Student) user).setPassword(contraseña);
            ((Student) user).setName(nombre);
            ((Student) user).setBirthdate(fecha);
            tipo = "student";
        } else {
            user = new Teacher();
            ((Teacher) user).setUserName(usuario);
            ((Teacher) user).setPassword(contraseña);
            ((Teacher) user).setName(nombre);
            ((Teacher) user).setBirthdate(fecha);
            ((Teacher) user).setCareer(carrera);
            tipo = "teacher";
        }

        try (ObjectOutputStream outputStream = new ObjectOutputStream(new FileOutputStream(rutaCompleta))) {
            outputStream.writeObject(user);
        } catch (IOException e) {
            e.printStackTrace();
        }

        guardarUsuario(usuario, contraseña, rutaCompleta, tipo);

        this.dispose();
    }//GEN-LAST:event_jButtonguardarregistroActionPerformed

    private void jRadioProfesoregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProfesoregisterActionPerformed
  jLabel3.setVisible(true);
    jTextcarreraprof.setVisible(true);
    }//GEN-LAST:event_jRadioProfesoregisterActionPerformed
    private void ShowJPanel(JPanel p){
        p.setSize(647,645);
        p.setLocation(0, 0);
        
        jPanel3.removeAll();
        jPanel3.add(p, BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }
    private void jTextcarreraprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcarreraprofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcarreraprofActionPerformed

    private void jTextdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdiaActionPerformed

    private void jTextmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextmesActionPerformed

    private void jTextnameuserregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnameuserregisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnameuserregisterActionPerformed

    private void jRadioEstudianteregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEstudianteregisterActionPerformed
    jLabel3.setVisible(false);
    jTextcarreraprof.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEstudianteregisterActionPerformed

    private void jTextcontraseñaregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcontraseñaregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcontraseñaregistroActionPerformed

    private void jTextNomyApelliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomyApelliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomyApelliActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonguardarregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioEstudianteregister;
    private javax.swing.JRadioButton jRadioProfesoregister;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextNomyApelli;
    private javax.swing.JTextField jTextaño;
    private javax.swing.JTextField jTextcarreraprof;
    private javax.swing.JTextField jTextcontraseñaregistro;
    private javax.swing.JTextField jTextdia;
    private javax.swing.JTextField jTextmes;
    private javax.swing.JTextField jTextnameuserregister;
    // End of variables declaration//GEN-END:variables
}
