package Interfaces.ProfesorUI.InterfazProfesor;

import Interfaces.Conexion;
import Interfaces.ProfesorUI.InterfazPanelesProfesor.Ejercicio;
import Interfaces.ProfesorUI.InterfazPanelesProfesor.Grupo;
import Interfaces.ProfesorUI.InterfazPanelesProfesor.PERFILES;
import java.awt.BorderLayout;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import rsscalelabel.RSScaleLabel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author USUARIO
 */
public class MenuProfesores extends javax.swing.JFrame {

    private Conexion conexion;
    public MenuProfesores(Conexion conexion) {
        this.conexion = conexion;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelGrupo = new javax.swing.JPanel();
        jButtonGrupo = new javax.swing.JButton();
        jButtonEjercicio = new javax.swing.JButton();
        jPanelEjercicio = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelPerfil = new javax.swing.JPanel();
        jButtonPerfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 620));

        jPanel1.setBackground(new java.awt.Color(3, 25, 38));

        jPanelGrupo.setBackground(new java.awt.Color(3, 25, 38));
        jPanelGrupo.setPreferredSize(new java.awt.Dimension(300, 170));

        jButtonGrupo.setBackground(new java.awt.Color(26, 40, 51));
        jButtonGrupo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonGrupo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resources/Grupos.png"))); // NOI18N
        jButtonGrupo.setText("Grupo");
        jButtonGrupo.setBorder(null);
        jButtonGrupo.setFocusPainted(false);
        jButtonGrupo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGrupo.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrupoActionPerformed(evt);
            }
        });

        jButtonEjercicio.setBackground(new java.awt.Color(26, 40, 51));
        jButtonEjercicio.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonEjercicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resources/Ejercicios.png"))); // NOI18N
        jButtonEjercicio.setText("Ejercicio");
        jButtonEjercicio.setBorder(null);
        jButtonEjercicio.setFocusPainted(false);
        jButtonEjercicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEjercicio.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGrupoLayout = new javax.swing.GroupLayout(jPanelGrupo);
        jPanelGrupo.setLayout(jPanelGrupoLayout);
        jPanelGrupoLayout.setHorizontalGroup(
            jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrupoLayout.createSequentialGroup()
                .addGroup(jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jButtonGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 96, Short.MAX_VALUE))
        );
        jPanelGrupoLayout.setVerticalGroup(
            jPanelGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrupoLayout.createSequentialGroup()
                .addComponent(jButtonGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButtonEjercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelEjercicio.setBackground(new java.awt.Color(3, 25, 38));

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                
            }
        });

        javax.swing.GroupLayout jPanelEjercicioLayout = new javax.swing.GroupLayout(jPanelEjercicio);
        jPanelEjercicio.setLayout(jPanelEjercicioLayout);
        jPanelEjercicioLayout.setHorizontalGroup(
            jPanelEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEjercicioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanelEjercicioLayout.setVerticalGroup(
            jPanelEjercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEjercicioLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanelPerfil.setBackground(new java.awt.Color(3, 25, 38));
        jPanelPerfil.setPreferredSize(new java.awt.Dimension(300, 170));

        jButtonPerfil.setBackground(new java.awt.Color(26, 40, 51));
        jButtonPerfil.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButtonPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resources/Perfil.png"))); // NOI18N
        jButtonPerfil.setText("Perfil");
        jButtonPerfil.setBorder(null);
        jButtonPerfil.setFocusPainted(false);
        jButtonPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonPerfil.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Juez Cachimbo");

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addComponent(jButtonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(241, 248, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 720));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ShowJPanel(JPanel p) {
        p.setSize(647, 645);
        p.setLocation(0, 0);

        jPanel2.removeAll();
        jPanel2.add(p, BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        conexion.cambiarPanelTeacher("PERFILES");
    }

    private void jButtonEjercicioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       conexion.cambiarPanelTeacher("Ejercicio");
    }

    private void jButtonGrupoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        conexion.cambiarPanelTeacher("Grupo");
    }

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
            conexion.cerrarSesionTeacher();  
        
    }                                        

   
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfesores(conexion).setVisible(true);
            }
        });
        
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEjercicio;
    private javax.swing.JButton jButtonGrupo;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEjercicio;
    private javax.swing.JPanel jPanelGrupo;
    private javax.swing.JPanel jPanelPerfil;
    // End of variables declaration//GEN-END:variables
}
